tools = [
   {
        "type": "function",
        "function": {
        "name": "add_numbers",
            "description": "Add two numbers",
            "parameters": {
                "type": "object",
                "properties": {
                    "num1": {
                        "type": "number",
                        "description": "The first number",
                    },
                    "num2": {
                        "type": "number",
                        "description": "The second number",
                    },
                },
                "required": ["num1", "num2"],
            },
        }
    },
    {
        "type": "function",
        "function": {
            "name": "generate_image",
            "description": "Generate an image using Dall-E 3 function",
            "parameters": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": """The prompt to generate image.""",
                    },
                    "size": {
                        "type": "string",
                        "enum": ["1024x1024", "other_sizes"],
                    },
                },
                "required": ["prompt"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "make_post_linkedin",
            "description": "make a post to linkedin",
            "parameters": {
                "type": "object",
                "properties": {
                    "linkedin_post": {
                        "type": "string",
                        "description": "The linkedin post text content starting with [FINAL CONTENT] tag",
                    },
                    "image": {
                        "type": "string",
                        "description": "Image URL of the post generated by generate_image function",
                    },
                },
                "required": ["linkedin_post"],
            },
        },
    },
   
]